version: '3'

services:
  db:
    container_name: odoo17-db
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo17@2024
      POSTGRES_DB: postgres
    restart: always 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    networks:
      - odoo-network
      
  odoo17:
    container_name: odoo17
    image: odoo:17
    depends_on:
      - db
    ports:
      - "18069:8069"
      - "18072:8072" # live chat
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2024
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      # - ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./odoo-addons:/mnt/extra-addons
      # - ./core/enterprise:/mnt/enterprise:ro
      - ./odoo-config/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo-logs/odoo17.log:/var/log/odoo/odoo-server.log
      - ./odoo-data:/var/lib/odoo
    restart: always     
    networks:
      - odoo-network        # run as a service


  nginx:
    image: nginx:latest
    container_name: odoo17-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - staticbuild:/app/public
      - ./odoo-nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - react-app
      - odoo17
    networks:
      - odoo-network
    restart: always
    tty: true   

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./odoo-nginx/certs/:/var/www/certbot/:rw

volumes:
  postgres-data:
  odoo-addons:
  odoo-config:
  odoo-nginx:
  odoo-data:
  odoo-logs:

networks:
  odoo-network:
    driver: bridge